# Generated by Django 5.1.6 on 2025-02-23 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollect.room')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('heat_index', models.FloatField()),
                ('pressure', models.FloatField(blank=True, default=1000.0)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollect.sensor')),
            ],
        ),
    ]
