# Generated by Django 5.1.6 on 2025-02-23 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 14, 1, 20, 447505)),
            preserve_default=False,
        ),
    ]
