"""readings table

Revision ID: ef3178b86f2a
Revises: d92297ad38a3
Create Date: 2025-02-21 18:20:17.535176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3178b86f2a'
down_revision = 'd92297ad38a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('room', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_sensor_room'), ['room'], unique=False)

    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('heat_index', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sensor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_sensor'), ['sensor'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_timestamp'))
        batch_op.drop_index(batch_op.f('ix_reading_sensor'))

    op.drop_table('reading')
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_room'))
        batch_op.drop_index(batch_op.f('ix_sensor_name'))

    op.drop_table('sensor')
    # ### end Alembic commands ###
